name: Secrets Scanner

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Run secrets scanner
        run: |
          echo "running secrets scanner workflow"
